export const UI_TEXT = {
  appName: "Hermes Agent UI",
  panes: {
    chat: "Chat",
    artifacts: "Artifacts / Preview",
    reasoning: "Reasoning Trace",
  },
  actions: {
    send: "Send",
    runBenchmark: "Run Benchmark",
    runDemo: "Run Demo",
    placeholder: "Ask Hermes...",
  },
  labels: {
    online: "online",
    offline: "offline",
    artifactPlaceholder: "Artifact preview panel placeholder (markdown/html/image can be rendered here).",
    preview: "Preview",
    toolLogs: "Tool Logs",
    noToolLogs: "No tool logs yet.",
    artifacts: "Artifacts",
    truncatedByServer: "Content truncated by server.",
    originalLength: "Original length",
    debug: "Debug",
    lastSeq: "last_seq",
    resumeSent: "resume_sent",
    reconnectAttempts: "reconnect_attempts",
    queuedMessages: "queued_messages",
    replayHits: "replay_hits",
    replayMisses: "replay_misses",
    artifactTruncated: "artifact_truncated",
    diagnostics: "Diagnostics",
    demoTemplates: "Demo Templates",
    policyBlocked: "Blocked by security policy. Rendered as plain text.",
    blockReason: "block_reason",
    virtualizedMode: "virtualized_mode",
    renderedWindow: "rendered_window",
    fps: "fps",
    droppedFrames: "dropped_frames",
  },
  states: {
    thinking: "Thinking",
    responding: "Responding",
    disconnected: "Disconnected",
    idle: "Idle",
  },
} as const;
